version: "3"

services:
    minesweeper-api:
        build: ./backend
        container_name: minesweeper-api
        ports:
            - 3000:3000
        volumes:
            - ./backend:/go/src/minesweeper