version: "3"

services:
    api:
        build: ./backend
        container_name: minesweeper-api
        ports:
            - "$API_PORT:80"
        volumes:
            - ./backend:/go/src/minesweeper
        env_file:
            - .env

    client:
        build: ./frontend
        container_name: minesweeper-client
        ports:
            - "$CLIENT_PORT:80"
        volumes:
            - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        env_file:
            - .env

    db:
        container_name: minesweeper-mongo
        image: mongo
        ports: 
            - 27017-27019:27017-27019
        environment:
            MONGO_INITDB_DATABASE: $MONGO_DATABASE
            MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
        volumes:
            # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongo:/data/db
        command: --quiet